//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorityHour
    {
        public int Authority_Id { get; set; }
        public int Hour_Id { get; set; }
        public string Name { get; set; }
    
        public virtual Authority Authority { get; set; }
        public virtual Hour Hour { get; set; }
    }
}
