//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Authority()
        {
            this.AuthorityNumber = new HashSet<AuthorityNumber>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.TimeSpan> Open { get; set; }
        public Nullable<System.TimeSpan> Close { get; set; }
        public Nullable<int> Address_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorityNumber> AuthorityNumber { get; set; }
    }
}
