//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tusjoseEntities : DbContext
    {
        public tusjoseEntities()
            : base("name=tusjoseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Access { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Authority> Authority { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Hour> Hour { get; set; }
        public virtual DbSet<Number> Number { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
