//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hour()
        {
            this.AuthorityHour = new HashSet<AuthorityHour>();
        }
    
        public int Id { get; set; }
        public Nullable<System.TimeSpan> Open { get; set; }
        public Nullable<System.TimeSpan> Close { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorityHour> AuthorityHour { get; set; }
    }
}
